package com.iudigital.crud.presentacion;

import com.iudigital.crud.controller.FuncionarioController;
import com.iudigital.crud.domain.Funcionario;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    private final FuncionarioController funcionarioController;
    private static final String[] COLUMNS = {"ID", "TIPO DE IDENTIFICACION","NUMERO DE IDENTIFICACION",
    "NOMBRES", "APELLIDOS" , "SEXO" , "DIRECCION" , "TELEFONO", "FECHA DE NACIMIENTO" , "ESTADO CIVIL"};
    private static final String SELECCIONE = "--SELECCIONE--";
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        txtFuncionarioId.setEditable(false);
        funcionarioController = new FuncionarioController();
        listFuncionarios();
        addListener();
        
    }
    
    private void listFuncionarios() {
        cbxFuncionarios.removeAllItems();
        Funcionario funcionario1 = new Funcionario();
        funcionario1.setNombres(SELECCIONE); 
        funcionario1.setApellidos(" ");// funcionario1.setTipo_identificacion(SELECCIONE);
        cbxFuncionarios.addItem(funcionario1);      
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        for(String COLUMN : COLUMNS){
            defaultTableModel.addColumn(COLUMN);
        }
        
        tblFuncionarios.setModel(defaultTableModel);
        
        try {
            
            List<Funcionario> funcionarios = funcionarioController.obtenerFuncionarios();
            if (funcionarios.isEmpty()) {
                return;
            }
            defaultTableModel.setRowCount(funcionarios.size());
            int row = 0;
            for (Funcionario funcionario : funcionarios) {
                defaultTableModel.setValueAt(funcionario.getId(), row, 0);
                defaultTableModel.setValueAt(funcionario.getTipo_identificacion(), row, 1);
                defaultTableModel.setValueAt(funcionario.getNumero_identificacion(), row, 2);
                defaultTableModel.setValueAt(funcionario.getNombres(), row, 3);
                defaultTableModel.setValueAt(funcionario.getApellidos(), row, 4);
                defaultTableModel.setValueAt(funcionario.getSexo(), row, 5);
                defaultTableModel.setValueAt(funcionario.getDireccion(), row, 6);
                defaultTableModel.setValueAt(funcionario.getTelefono(), row, 7);
                defaultTableModel.setValueAt(funcionario.getFecha_nacimiento(), row, 8);
                defaultTableModel.setValueAt(funcionario.getEstado_civil(), row, 9);
                row++;
                
                cbxFuncionarios.addItem(funcionario);
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    // esta se implementa para validar si la variable seleccione es igual a la misma es por que aun el usuario no ha escogido el usuario
    private void addListener(){
        cbxFuncionarios.addItemListener(event -> {
        Funcionario selectedFuncionario = (Funcionario) event.getItem();
        if(selectedFuncionario.getNombres().equals(SELECCIONE)){ //if(selectedFuncionario.getTipo_identificacion().equals(SELECCIONE))
            txtFuncionarioId.setText("");
            txtDocumentTypeEdit.setText("");
            txtIdentificationNumberEdit.setText("");
            txtNameEdit.setText("");
            txtLastNameEdit.setText("");
            txtSexEdit.setText("");
            txtAddressEdit.setText("");
            txtPhoneEdit.setText("");
            txtDateEdit.setText("");
            txtCivilStatusEdit.setText("");
        } else {
            txtFuncionarioId.setText(String.valueOf(selectedFuncionario.getId()));
            txtDocumentTypeEdit.setText(selectedFuncionario.getTipo_identificacion());
            txtIdentificationNumberEdit.setText(selectedFuncionario.getNumero_identificacion());
            txtNameEdit.setText(selectedFuncionario.getNombres());
            txtLastNameEdit.setText(selectedFuncionario.getApellidos());
            txtSexEdit.setText(selectedFuncionario.getSexo());
            txtAddressEdit.setText(selectedFuncionario.getDireccion());
            txtPhoneEdit.setText(selectedFuncionario.getTelefono());
            txtDateEdit.setText(selectedFuncionario.getFecha_nacimiento());
            txtCivilStatusEdit.setText(selectedFuncionario.getEstado_civil());
        }    
        });      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanels = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxFuncionarios = new javax.swing.JComboBox<>();
        lblfuncionarioId = new javax.swing.JLabel();
        txtFuncionarioId = new javax.swing.JTextField();
        lblDocumentTypeEdit = new javax.swing.JLabel();
        txtDocumentTypeEdit = new javax.swing.JTextField();
        lblIdentificationNumberEdit = new javax.swing.JLabel();
        txtIdentificationNumberEdit = new javax.swing.JTextField();
        lblNameEdit = new javax.swing.JLabel();
        txtNameEdit = new javax.swing.JTextField();
        lblLastNameEdit = new javax.swing.JLabel();
        txtLastNameEdit = new javax.swing.JTextField();
        lblSexEdit = new javax.swing.JLabel();
        txtSexEdit = new javax.swing.JTextField();
        lblAddressEdit = new javax.swing.JLabel();
        txtAddressEdit = new javax.swing.JTextField();
        lblPhoneEdit = new javax.swing.JLabel();
        txtPhoneEdit = new javax.swing.JTextField();
        lblDateEdit = new javax.swing.JLabel();
        txtDateEdit = new javax.swing.JTextField();
        lblCivilStatusEdit = new javax.swing.JLabel();
        txtCivilStatusEdit = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblIdentificationNumber = new javax.swing.JLabel();
        txtIdentificationNumber = new javax.swing.JTextField();
        lblSex = new javax.swing.JLabel();
        txtSex = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtCivilStatus = new javax.swing.JTextField();
        lblCivilStatus = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        lblDocumentType = new javax.swing.JLabel();
        txtDocumentType = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ADMINISTRACION DE FUNCIONARIOS ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualice los siguientes campos"));

        jLabel2.setText("FUNCIONARIOS");

        cbxFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFuncionariosActionPerformed(evt);
            }
        });

        lblfuncionarioId.setText("ID");

        lblDocumentTypeEdit.setText("TIPO DE DOC");

        lblIdentificationNumberEdit.setText("NUMERO DE IDENTIFICACION");

        lblNameEdit.setText("NOMBRE");

        txtNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameEditActionPerformed(evt);
            }
        });

        lblLastNameEdit.setText("APELLIDO");

        txtLastNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameEditActionPerformed(evt);
            }
        });

        lblSexEdit.setText("SEXO");

        txtSexEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSexEditActionPerformed(evt);
            }
        });

        lblAddressEdit.setText("DIRECCION");

        txtAddressEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressEditActionPerformed(evt);
            }
        });

        lblPhoneEdit.setText("TELEFONO");

        lblDateEdit.setText("NACIMIENTO");

        lblCivilStatusEdit.setText("ESTADO CIVIL");

        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("ELIMINAR");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblfuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lblDocumentTypeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdentificationNumberEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDocumentTypeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIdentificationNumberEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(txtNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLastNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastNameEdit))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSexEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAddressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSexEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAddressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblPhoneEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDateEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCivilStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDateEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCivilStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfuncionarioId)
                    .addComponent(lblDocumentTypeEdit)
                    .addComponent(lblIdentificationNumberEdit)
                    .addComponent(lblNameEdit)
                    .addComponent(lblLastNameEdit)
                    .addComponent(lblSexEdit)
                    .addComponent(lblAddressEdit)
                    .addComponent(lblPhoneEdit)
                    .addComponent(lblDateEdit)
                    .addComponent(lblCivilStatusEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuncionarioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumentTypeEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentificationNumberEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCivilStatusEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanels.addTab("Actualizar - Eliminar Carro", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite los siguientes campos"));

        lblName.setText("NOMBRE");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblLastName.setText("APELLIDO");

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblIdentificationNumber.setText("NUMERO DE IDENTIFICACION");

        txtIdentificationNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificationNumberActionPerformed(evt);
            }
        });

        lblSex.setText("SEXO");

        lblAddress.setText("DIRECCION");

        lblPhone.setText("TELEFONO");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        lblDate.setText("NACIMIENTO");

        lblCivilStatus.setText("ESTADO CIVIL");

        btnCreate.setText("GUARDAR");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        lblDocumentType.setText("TIPO DE DOC");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtDocumentType, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDocumentType, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblSex, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName)
                    .addComponent(lblLastName)
                    .addComponent(lblSex)
                    .addComponent(lblAddress)
                    .addComponent(lblPhone)
                    .addComponent(lblDate)
                    .addComponent(lblCivilStatus)
                    .addComponent(lblDocumentType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCivilStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdentificationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDocumentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(19, 19, 19))
        );

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 998, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanels.addTab("Crear - Listar Funcionarios", jPanel1);

        getContentPane().add(jPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1010, 510));

        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtIdentificationNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificationNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificationNumberActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        
        if (txtDocumentType.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el tipo de documento");
            txtDocumentType.requestFocus();
            return;
        }

        if (txtIdentificationNumber.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el numero de documento");
            txtIdentificationNumber.requestFocus();
            return;
        }

        if (txtName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el nombre");
            txtName.requestFocus();
            return;
        }

        if (txtLastName.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el apellido");
            txtLastName.requestFocus();
            return;
        }

        if (txtSex.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite su sexo");
            txtSex.requestFocus();
            return;
        }

        if (txtAddress.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite su direccion");
            txtAddress.requestFocus();
            return;
        }

        if (txtPhone.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite su numero de celular");
            txtPhone.requestFocus();
            return;
        }

        if (txtDate.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la fecha de su nacimiento");
            txtDate.requestFocus();
            return;
        }

        if (txtCivilStatus.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite su estado civil");
            txtCivilStatus.requestFocus();
            return;
        }

        try {

            Funcionario funcionario = new Funcionario();
            funcionario.setTipo_identificacion(txtDocumentType.getText().trim());
            funcionario.setNumero_identificacion(txtIdentificationNumber.getText().trim()); // (String.valueOf(selectedFuncionario.getId())
            funcionario.setNombres(txtName.getText().trim());
            funcionario.setApellidos(txtLastName.getText().trim());
            funcionario.setSexo(txtSex.getText().trim());
            funcionario.setDireccion(txtAddress.getText().trim());
            funcionario.setTelefono(txtPhone.getText().trim());
            funcionario.setFecha_nacimiento(txtDate.getText().trim());
            funcionario.setEstado_civil(txtCivilStatus.getText().trim());
            funcionarioController.crear(funcionario);
            
            txtDocumentType.setText("");
            txtIdentificationNumber.setText("");
            txtName.setText("");
            txtLastName.setText("");
            txtSex.setText("");
            txtAddress.setText("");
            txtPhone.setText("");
            txtDate.setText("");
            txtCivilStatus.setText("");
            listFuncionarios();
            JOptionPane.showMessageDialog(null, "Funcionario creado con exito");

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "No fue creado el funcionario");
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameEditActionPerformed

    private void txtAddressEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressEditActionPerformed

    private void txtSexEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexEditActionPerformed

    private void txtLastNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameEditActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if (txtFuncionarioId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccine el funcionario de la ista");
            txtFuncionarioId.requestFocus();
            return;
        }

        if (txtDocumentTypeEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el tipo de documento");
            txtDocumentTypeEdit.requestFocus();
            return;
        }

        if (txtIdentificationNumberEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el numero de documento");
            txtIdentificationNumberEdit.requestFocus();
            return;
        }

        if (txtNameEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el nombre");
            txtNameEdit.requestFocus();
            return;
        }

        if (txtLastNameEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite el apellido");
            txtLastNameEdit.requestFocus();
            return;
        }

        if (txtSexEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite su sexo");
            txtSexEdit.requestFocus();
            return;
        }

        if (txtAddressEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite su direccion");
            txtAddressEdit.requestFocus();
            return;
        }

        if (txtPhoneEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite su numero de celular");
            txtPhoneEdit.requestFocus();
            return;
        }

        if (txtDateEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite la fecha de su nacimiento");
            txtDateEdit.requestFocus();
            return;
        }

        if (txtCivilStatusEdit.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Digite su estado civil");
            txtCivilStatusEdit.requestFocus();
            return;
        }

        Funcionario funcionario = new Funcionario();
        funcionario.setTipo_identificacion(txtDocumentTypeEdit.getText().trim());
        funcionario.setNumero_identificacion(txtIdentificationNumberEdit.getText().trim()); // (String.valueOf(selectedFuncionario.getId())
        funcionario.setNombres(txtNameEdit.getText().trim());
        funcionario.setApellidos(txtLastNameEdit.getText().trim());
        funcionario.setSexo(txtSexEdit.getText().trim());
        funcionario.setDireccion(txtAddressEdit.getText().trim());
        funcionario.setTelefono(txtPhoneEdit.getText().trim());            
        funcionario.setFecha_nacimiento(txtDateEdit.getText().trim());
        funcionario.setEstado_civil(txtCivilStatusEdit.getText().trim());

        int opt = JOptionPane.showConfirmDialog(null, "¿Desea actualizar el funcionario?", "Confirmar salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opt == 0) {
            try {
                funcionarioController.actualizarFuncionario(Integer.parseInt(txtFuncionarioId.getText()), funcionario);
                txtFuncionarioId.setText("");
                txtDocumentTypeEdit.setText("");
                txtIdentificationNumberEdit.setText("");
                txtNameEdit.setText("");
                txtLastNameEdit.setText("");
                txtSexEdit.setText("");
                txtAddressEdit.setText("");
                txtPhoneEdit.setText("");
                txtDateEdit.setText("");
                txtCivilStatusEdit.setText("");
                listFuncionarios();
                JOptionPane.showMessageDialog(null, "Funcionario actualizado con exito");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Funcionario no fue actualizado");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cbxFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFuncionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFuncionariosActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if (txtFuncionarioId.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccine el funcionario de la ista");
            txtFuncionarioId.requestFocus();
            return;
        }

        int opt = JOptionPane.showConfirmDialog(null, "¿Estas seguro que deseas eliminar el dato?",
                "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opt == 0) {

            try {
                funcionarioController.eliminarFuncionario(Integer.parseInt(txtFuncionarioId.getText()));
                txtFuncionarioId.setText("");
                txtDocumentTypeEdit.setText("");
                txtIdentificationNumberEdit.setText("");
                txtNameEdit.setText("");
                txtLastNameEdit.setText("");
                txtSexEdit.setText("");
                txtAddressEdit.setText("");
                txtPhoneEdit.setText("");
                txtDateEdit.setText("");
                txtCivilStatusEdit.setText("");
                listFuncionarios();
                JOptionPane.showMessageDialog(null, "Funcionario eliminado  con exito");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Funcionario no fue eliminado");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Funcionario> cbxFuncionarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jPanels;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressEdit;
    private javax.swing.JLabel lblCivilStatus;
    private javax.swing.JLabel lblCivilStatusEdit;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateEdit;
    private javax.swing.JLabel lblDocumentType;
    private javax.swing.JLabel lblDocumentTypeEdit;
    private javax.swing.JLabel lblIdentificationNumber;
    private javax.swing.JLabel lblIdentificationNumberEdit;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastNameEdit;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameEdit;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneEdit;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblSexEdit;
    private javax.swing.JLabel lblfuncionarioId;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAddressEdit;
    private javax.swing.JTextField txtCivilStatus;
    private javax.swing.JTextField txtCivilStatusEdit;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDateEdit;
    private javax.swing.JTextField txtDocumentType;
    private javax.swing.JTextField txtDocumentTypeEdit;
    private javax.swing.JTextField txtFuncionarioId;
    private javax.swing.JTextField txtIdentificationNumber;
    private javax.swing.JTextField txtIdentificationNumberEdit;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLastNameEdit;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameEdit;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhoneEdit;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtSexEdit;
    // End of variables declaration//GEN-END:variables
}
